### Pandas

..>Pandas is a powerful python library for manipulation an analysis of data 

..>it is a open source library

..>fast(built on top of numpy),flexible(different resource),productive library

 ### Install

In [13]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\klemp\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\klemp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [14]:
import pandas as pd

In [15]:
 print(pd.__version__)

2.2.3

##### Series - One dimesional array(data structure) with label

In [16]:
l1 = [1,2,3,4,5]
type(l1)

list

In [17]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [18]:
s=pd.Series(l1,index=['a','b','c','d','e'] ,name="myseries")

In [19]:
s

a    1
b    2
c    3
d    4
e    5
Name: myseries, dtype: int64

In [20]:
s['a']

np.int64(1)

In [21]:
type(s)

pandas.core.series.Series

In [22]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [23]:
s.values

array([1, 2, 3, 4, 5])

In [24]:
s.index[0]='z' #####Index in series are immmutable(can't change)

TypeError: Index does not support mutable operations

In [ ]:
s.rename(index={'b':'y'},inplace=True)

In [ ]:
s

a    1
y    2
c    3
d    4
e    5
Name: myseries, dtype: int64

In [ ]:
s=s.rename(index={'b':'y'})

In [ ]:
s

a    1
y    2
c    3
d    4
e    5
Name: myseries, dtype: int64

######DataFrame-Its a 2d array

In [ ]:
dict1={'Name':['Virat','Rohit','Dhoni','Jadeja','Bumra','Virat'],
       'age':[34,33,40,32,30,30],
       'marks':[85,90,75,80,70,100],
       'role':['Batsman','Batsman','Wicket keeper','All rounder','Bowler','bowler']
       }
df=pd.DataFrame(dict1)

In [ ]:
df

     Name  age  marks           role
0   Virat   34     85        Batsman
1   Rohit   33     90        Batsman
2   Dhoni   40     75  Wicket keeper
3  Jadeja   32     80    All rounder
4   Bumra   30     70         Bowler
5    Salt   30    100         bowler

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head(1)

    Name  age  marks     role
0  Virat   34     85  Batsman

In [ ]:
df.tail(1)

   Name  age  marks    role
5  Salt   30    100  bowler

In [ ]:
len(df)

6

In [ ]:
df.count()

Name     6
age      6
marks    6
role     6
dtype: int64

In [ ]:
df.columns

Index(['Name', 'age', 'marks', 'role'], dtype='object')

In [ ]:
df['Name']

0     Virat
1     Rohit
2     Dhoni
3    Jadeja
4     Bumra
5      Salt
Name: Name, dtype: object

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df['Name'].value_counts()

Name
Virat     2
Rohit     1
Dhoni     1
Jadeja    1
Bumra     1
Name: count, dtype: int64

#### Basic operations

> importing data set from different files

> importing tabular dataset

In [29]:
stock_df=pd.read_csv(r'C:\Users\klemp\OneDrive\Desktop\applied data analyst\dataset\ETH_1h.csv')

In [30]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [ ]:
stock_df.head() # Top 5 rows

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [ ]:
stock_df.head(10) #Top 10 rows

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

##### Bottom 5 rows

In [33]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [34]:
## Number of rows in dataframe
len(stock_df)

23674

> Access column names of dataframe

In [35]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [36]:
### accessing a column in a dataframe
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [38]:
### Accessing multiple columns in array in a dataframe
### accessing a column in a dataframe
stock_df[['Open','Close','Volume']]

         Open   Close      Volume
0      129.94  128.71  1940673.93
1      119.51  129.94  7579741.09
2      124.47  119.51  4898735.81
3      124.08  124.47  2753450.92
4      124.85  124.08  4461424.71
...       ...     ...         ...
23669  265.74  272.57  1500282.55
23670  268.79  265.74  1702536.85
23671  274.83  268.79  3010787.99
23672  275.01  274.83   824362.87
23673  279.98  275.01   679358.87

[23674 rows x 3 columns]

# Accessing rows of dataframe

In [39]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [40]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

# Accessing rows
Loc-label location

In [46]:
stock_df.loc[23672,['Date','Open','Close']]

Date     2017-07-01 12-PM
Open               275.01
Close              274.83
Name: 23672, dtype: object

In [47]:
l=[1,2,3,4]
l[1:4]

[2, 3, 4]

In [49]:
d2=[[1,2,3],
    [4,5,6],
    [7,8,9]]
d2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [50]:
d2[0][1]

2

In [51]:
d2[1][1:3]

[5, 6]

# Slicing in loc(labeled location)

In [52]:
stock_df.loc[23672,'Open':'Close'] #Inclusive

Open     275.01
High     275.01
Low       271.0
Close    274.83
Name: 23672, dtype: object

# iloc -index based location,when we dont know labels for rows and columns

In [56]:
stock_df.iloc[1,2]

np.float64(119.51)

In [ ]:
stock_df.iloc[3,[2,4]] #multiple columns

Open    124.08
Low     121.63
Name: 3, dtype: object

In [ ]:
stock_df.iloc[2,2:6] #slicing

Open     124.47
High     124.85
Low       115.5
Close    119.51
Name: 2, dtype: object

In [58]:
stock_df.iloc[1:6,2:6]

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

# Filtering

In [59]:
stock_df['High']>130

0         True
1         True
2        False
3        False
4        False
         ...
23669     True
23670     True
23671     True
23672     True
23673     True
Name: High, Length: 23674, dtype: bool

In [60]:
f1=stock_df['High']>130

stock_gt_130=stock_df[f1]

In [61]:
stock_gt_130.reset_index(drop=True,inplace=True)

In [62]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

# Adding new column

In [70]:
stock_df['Random_col']=list(range(1,len(stock_df)+1))

In [65]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [67]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Open                279.98
High                279.99
Low                  272.1
Close               275.01
Volume           679358.87
Name: 23673, dtype: object

In [64]:
len(stock_df)

23674

In [68]:
for i in range(0,3):
    print(i)

0
1
2

In [71]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,Random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5
...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674

# Droping columns

In [78]:
stock_df.drop(columns=['High','Open'],inplace=True)

In [79]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23668  2017-07-01 04-PM  ETHUSD  267.60  268.00  1287300.75
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87

[23673 rows x 5 columns]

In [74]:
stock_df.drop(columns=['Random_col'],inplace=True)

In [75]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

# Droping rows

In [76]:
stock_df.drop(23673,axis=0,inplace=True)

In [77]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23668  2017-07-01 04-PM  ETHUSD  272.57  272.57  267.60  268.00  1287300.75
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87

[23673 rows x 7 columns]